name: Staging Server Update

on: 
  push:
    branches:
      - develop

jobs:
  update:
    name: Big server
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        debug: true
        script: ./hello_this_is_juan.sh